In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('../data/sample.csv')

In [5]:
df.head()

,id,client_id,card_brand,card_type,card_number,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,expires_date
0,4524,825,Visa,Debit,4344676511950444,623,YES,2,$24295,09/2002,2022,No,2032-03-01
1,2731,825,Visa,Debit,4956965974959986,393,YES,2,$21968,04/2014,2014,No,2028-12-01
2,3701,825,Visa,Debit,4582313478255491,719,YES,2,$46414,07/2003,2004,No,2030-11-01
3,4537,1746,Visa,Credit,4404898874682993,736,YES,1,$27500,09/2003,2026,No,2030-07-01
4,1278,1746,Visa,Debit,4001482973848631,972,YES,2,$28508,02/2011,2025,No,2034-09-01

In [6]:
print("Rows and Columns:", df.shape)

Rows and Columns: (4314, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4314 entries, 0 to 4313
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     4314 non-null   int64
 1   client_id              4314 non-null   int64
 2   card_brand             4314 non-null   object
 3   card_type              4314 non-null   object
 4   card_number            4314 non-null   int64
 5   cvv                    4314 non-null   int64
 6   has_chip               4314 non-null   object
 7   num_cards_issued       4314 non-null   int64
 8   credit_limit           4314 non-null   object
 9   acct_open_date         4314 non-null   object
 10  year_pin_last_changed  4314 non-null   int64
 11  card_on_dark_web       4314 non-null   object
 12  expires_date           3067 non-null   object
dtypes: int64(6), object(7)
memory usage: 438.3+ KB

In [8]:
df.describe()

,id,client_id,card_number,cvv,num_cards_issued,year_pin_last_changed
count,4314.000000,4314.000000,4.314000e+03,4314.000000,4314.000000,4314.000000
mean,3581.178720,995.873667,5.145624e+15,556.379694,1.507186,2018.061428
std,1480.906085,583.675131,6.196444e+14,257.685622,0.516879,5.957355
min,1000.000000,0.000000,4.000393e+15,100.000000,1.000000,2002.000000
25%,2288.250000,482.250000,4.648847e+15,332.000000,1.000000,2013.000000
50%,3583.000000,989.000000,5.178531e+15,564.000000,1.000000,2019.000000
75%,4861.750000,1509.000000,5.625908e+15,781.750000,2.000000,2024.000000
max,6145.000000,1999.000000,6.997197e+15,999.000000,3.000000,2026.000000

In [9]:
df.columns.tolist()

['id',
 'client_id',
 'card_brand',
 'card_type',
 'card_number',
 'cvv',
 'has_chip',
 'num_cards_issued',
 'credit_limit',
 'acct_open_date',
 'year_pin_last_changed',
 'card_on_dark_web',
 'expires_date']