In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/sample.csv')

In [4]:
df.head()

,id,client_id,card_brand,card_type,card_number,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,expires_date
0,4524,825,Visa,Debit,4344676511950444,623,YES,2,$24295,09/2002,2022,No,2032-03-01
1,2731,825,Visa,Debit,4956965974959986,393,YES,2,$21968,04/2014,2014,No,2028-12-01
2,3701,825,Visa,Debit,4582313478255491,719,YES,2,$46414,07/2003,2004,No,2030-11-01
3,4537,1746,Visa,Credit,4404898874682993,736,YES,1,$27500,09/2003,2026,No,2030-07-01
4,1278,1746,Visa,Debit,4001482973848631,972,YES,2,$28508,02/2011,2025,No,2034-09-01

In [6]:
from datetime import datetime

current_year = datetime.now().year

df["acct_open_date"] = pd.to_datetime(
    df["acct_open_date"],
    format="%m/%Y"
)

In [7]:
df["account_age"] = (
    current_year - df["acct_open_date"].dt.year
)

In [8]:
df[["acct_open_date", "account_age"]].head()

  acct_open_date  account_age
0     2002-09-01           24
1     2014-04-01           12
2     2003-07-01           23
3     2003-09-01           23
4     2011-02-01           15

In [9]:
df["pin_age"] = (
    current_year - df["year_pin_last_changed"]
)

In [10]:
df[["year_pin_last_changed", "pin_age"]].head()

   year_pin_last_changed  pin_age
0                   2022        4
1                   2014       12
2                   2004       22
3                   2026        0
4                   2025        1

In [11]:
df["expires_date"] = pd.to_datetime(
    df["expires_date"]
)

In [12]:
df["years_to_expiry"] = (
    df["expires_date"].dt.year - current_year
)

In [13]:
df[["expires_date", "years_to_expiry"]].head()

  expires_date  years_to_expiry
0   2032-03-01              6.0
1   2028-12-01              2.0
2   2030-11-01              4.0
3   2030-07-01              4.0
4   2034-09-01              8.0

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["card_brand_encoded"] = le.fit_transform(
    df["card_brand"]
)

In [16]:
df[["card_brand", "card_brand_encoded"]].tail()

      card_brand  card_brand_encoded
4309  Mastercard                   1
4310  Mastercard                   1
4311        Visa                   2
4312  Mastercard                   1
4313        Visa                   2

In [17]:
df[[
    "account_age",
    "pin_age",
    "years_to_expiry",
    "card_brand_encoded"
]].head()

   account_age  pin_age  years_to_expiry  card_brand_encoded
0           24        4              6.0                   2
1           12       12              2.0                   2
2           23       22              4.0                   2
3           23        0              4.0                   2
4           15        1              8.0                   2

In [19]:
df["has_chip"] = df["has_chip"].map({
    "YES": 1,
    "NO": 0
})

In [20]:
df["has_chip"].head()

0    1
1    1
2    1
3    1
4    1
Name: has_chip, dtype: int64

In [21]:
df["has_chip"].dtype

dtype('int64')

In [23]:
df["card_type"].unique()

array(['Debit', 'Credit', 'Debit (Prepaid)'], dtype=object)

In [24]:
df["card_type"] = df["card_type"].map({
    "Debit": 0,
    "Credit": 1
})

In [25]:
df["card_type"].head()

0    0.0
1    0.0
2    0.0
3    1.0
4    0.0
Name: card_type, dtype: float64

In [27]:
df["card_on_dark_web"].unique()

array(['No'], dtype=object)

In [28]:
df["card_on_dark_web"] = df["card_on_dark_web"].map({
    "No": 0,
    "Yes": 1
})

In [32]:
df["card_brand"] = df["card_brand"].map({
    "America Express": 0,
    "Mastercard": 1,
    "Visa": 2
})

In [29]:
df["card_on_dark_web"].head()

0    0
1    0
2    0
3    0
4    0
Name: card_on_dark_web, dtype: int64

In [37]:
df['credit_limit'] = df['credit_limit'].str.replace('$', '').astype(float)

In [40]:
df['card_type'] = df['card_type'].fillna(1.0)

In [56]:
df = df.drop(columns=['id', 'client_id', 'card_number', 'cvv', 'expires_date'])

KeyError: "['id', 'client_id', 'card_number', 'cvv', 'expires_date'] not found in axis"

In [ ]:
df['card_brand'] = df['card_brand'].fillna(df['card_brand'].mode()[0])

In [52]:
df.isnull().sum()

card_brand                  0
card_type                   0
has_chip                    0
num_cards_issued            0
credit_limit                0
acct_open_date              0
year_pin_last_changed       0
card_on_dark_web            0
account_age                 0
pin_age                     0
years_to_expiry          1247
card_brand_encoded          0
dtype: int64

In [58]:
df = df.drop(columns=['years_to_expiry'])

In [51]:
df.head(10)

,card_brand,card_type,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,account_age,pin_age,years_to_expiry,card_brand_encoded
0,2.0,0.0,1,2,24295.0,2002-09-01,2022,0,24,4,6.0,2
1,2.0,0.0,1,2,21968.0,2014-04-01,2014,0,12,12,2.0,2
2,2.0,0.0,1,2,46414.0,2003-07-01,2004,0,23,22,4.0,2
3,2.0,1.0,1,1,27500.0,2003-09-01,2026,0,23,0,4.0,2
4,2.0,0.0,1,2,28508.0,2011-02-01,2025,0,15,1,8.0,2
5,1.0,1.0,1,2,54.0,2010-06-01,2015,0,16,11,9.0,1
6,1.0,1.0,1,1,99.0,2006-07-01,2026,0,20,0,5.0,1
7,1.0,0.0,1,2,31599.0,2009-10-01,2024,0,17,2,5.0,1
8,1.0,0.0,0,2,27480.0,2002-03-01,2022,0,24,4,6.0,1
9,1.0,0.0,1,1,26743.0,2019-03-01,2019,0,7,7,3.0,1

In [59]:
df.to_csv("../data/engineered_data.csv", index=False)